CREATE SCHEMA IF NOT EXISTS financeiro
    AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS financeiro.despesa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    credor character varying(255) COLLATE pg_catalog."default",
    data_protocolo date NOT NULL,
    date_vencimento date NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    numero_protocolo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(16,2),
    id_status integer NOT NULL,
    id_tipo integer NOT NULL,
    CONSTRAINT despesa_pkey PRIMARY KEY (id),
    CONSTRAINT uk_n7uxif67o0se2s46qtwhodxcb UNIQUE (numero_protocolo),
    CONSTRAINT fk3rdry5djdfk2jetvr3v7ln7yt FOREIGN KEY (id_status)
        REFERENCES financeiro.status_despesa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk4ejhsf5amrvb6llkd57i7pw9s FOREIGN KEY (id_tipo)
        REFERENCES financeiro.tipo_despesa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS financeiro.despesa
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS financeiro.empenho
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano integer NOT NULL,
    data date NOT NULL,
    numero integer NOT NULL,
    observacao character varying(255) COLLATE pg_catalog."default",
    valor numeric(16,2) NOT NULL,
    id_despesa bigint,
    CONSTRAINT empenho_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aaamtd8458p3sbq8cmiuu1q2o UNIQUE (numero),
    CONSTRAINT fkjsctb9nobtmy1ccs3fihvlmr8 FOREIGN KEY (id_despesa)
        REFERENCES financeiro.despesa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS financeiro.empenho
    OWNER to postgres;



CREATE TABLE IF NOT EXISTS financeiro.pagamento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano integer NOT NULL,
    data date NOT NULL,
    numero integer NOT NULL,
    observacao character varying(255) COLLATE pg_catalog."default",
    valor numeric(16,2) NOT NULL,
    id_empenho bigint,
    CONSTRAINT pagamento_pkey PRIMARY KEY (id),
    CONSTRAINT uk_wfcncfh6pk4myrt9vgmn83nx UNIQUE (numero),
    CONSTRAINT fkcl9e5r057tw9nj2uqt1jmp59u FOREIGN KEY (id_empenho)
        REFERENCES financeiro.empenho (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS financeiro.pagamento
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS financeiro.status_despesa
(
    id integer NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT status_despesa_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS financeiro.status_despesa
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS financeiro.tipo_despesa
(
    id integer NOT NULL,
    descricao character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipo_despesa_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS financeiro.tipo_despesa
    OWNER to postgres;









